update minimal db build for testing on fork

diff --git a/.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml b/.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
--- a/.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
+++ b/.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
@@ -35,11 +35,27 @@ jobs:
     uses: ./.github/workflows/Find Standard and Extension Versions.yml
     with:
       calling_branch: ${{ github.head_ref || github.ref_name }}
+	  
+	services:
+      mssql:
+        image: mcr.microsoft.com/mssql/server:2019-latest
+		volumes:
+          - SQLServerDataVolume:/var/opt/mssql
+        env:
+          ACCEPT_EULA: Y
+          SA_PASSWORD: ${{ env.DB_PASS }}
+        ports:
+          - 1433:1433
+        options: >-
+          --health-cmd "exit 0" 
+          --health-interval 10s 
+          --health-timeout 5s 
+          --health-retries 3
 
   build:
     if: ${{ always() }}
     needs: FindStandardAndExtensionVersions
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     strategy:
       matrix:
         StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
@@ -48,22 +64,22 @@ jobs:
     steps:
     - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
       run:  echo "${{ github.event.inputs.distinct_id }}"
-    - name: Check for Azure token
-      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: | 
-        echo "::error::Missing Azure Token"
-        exit 1 
+    # - name: Check for Azure token
+    #   if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+    #   run: | 
+    #     echo "::error::Missing Azure Token"
+    #     exit 1 
     - name: Support longpaths
       run: git config --system core.longpaths true
     - name: Checkout Ed-Fi-ODS
       uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
       with:
-          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
+          repository: mjaksn/Ed-Fi-ODS
           path: Ed-Fi-ODS/
     - name: Checkout Ed-Fi-ODS-Implementation
       uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
       with:
-          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
+          repository: mjaksn/Ed-Fi-ODS-Implementation
           path: Ed-Fi-ODS-Implementation/
     - name: Set Ed-Fi-Standard Reference
       working-directory: ./Ed-Fi-ODS/
@@ -75,7 +91,7 @@ jobs:
     - name: Checkout Ed-Fi-Data-Standard
       uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
       with:
-          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Data-Standard
+          repository: mjaksn/Ed-Fi-Data-Standard
           path: Ed-Fi-Data-Standard/
           ref: ${{ env.EDFI_STANDARD_REFERENCE }}
     - name: Is pull request branch exists in Ed-Fi-ODS-Implementation
@@ -91,11 +107,6 @@ jobs:
                 echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
             }
       shell: pwsh
-    - name: Install sql-server-2019 & sqlpackage
-      shell: powershell
-      run: |
-          choco install sql-server-2019  -y --params "'/IGNOREPENDINGREBOOT /IACCEPTSQLSERVERLICENSETERMS /Q /ACTION=install /INSTANCEID=MSSQLSERVER /INSTANCENAME=MSSQLSERVER /TCPENABLED=1 /UPDATEENABLED=FALSE /FEATURES=SQL,Tools'" --execution-timeout=$installTimeout
-          choco install sqlpackage
     - name: Cache Nuget packages
       uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 #v4.0.1
       with:
@@ -121,7 +132,7 @@ jobs:
       working-directory: ./Ed-Fi-ODS-Implementation/
       run: |
         $ErrorActionPreference = 'Stop'
-        rm -R "./Plugin/Extensions.*"
+        rm -r Plugin/Extensions.*
       shell: powershell 
     - name: Create Database Template (no extensions)
       working-directory: ./
